#!/usr/bin/env bash

set -e

include_remote=""
track=""

while getopts ":a" opt; do
  case $opt in
    a)
      include_remote="-a"
      track="-t"
      shift
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

pattern=$1

branches=($(echo `git branch $include_remote --list *$pattern* | tr '* ' ' '`))

if [ ${#branches[@]} -eq 0 ]; then
    if [ -z $include_remote ]; then
        echo "No local branches found"
        read -p "Do you want to include remote branches? (y/n): " yn
        case $yn in
            [Yy]*) $0 -a $pattern;;
            [Nn]*) exit 0;;
            *) exit 1;;
        esac
    else
        echo "No remote branches found"
        exit 1
    fi
elif [ ${#branches[@]} -eq 1 ]; then
    git checkout $track $branches
else
    PS3="Select an option: "
    select option in "${branches[@]}"; do
        git checkout $track $option
        break
    done
fi
